export const EXPERIENCE_LIST_ITEMS = [
  `Water pump replacement `,
  `Oil change`,
  `Brakes - pads and rotors replacement`,
  `Power steering line repair`,
  `Cam sensor replacement`,
  `Valve cover replacement`,
  `Cylinder head replacement`,
  `Engine install`,
  `Engine to torque converter`,
  `Spark plug and coil pack install`,
  `Intake manifold installation `,
  `Exhaust manifold installation`,
  `Motor mount installation`,
  `Oil pan replacement`,
  `Transmission pan replacement`,
  `Exhaust system removal and reassembly`,
  `Starter replacement`,
  `Alternator install`,
  `Compressor install`,
  `Tire removal and reinstall`,
  `Wheel bearings replacement`,
  `Coolant hosing replacement`,
  `Bumper renewal`,
  `Driver/passenger seat removal and reinstall`,
  `Pcv hosing replacement`,
  `Interior detailing`,
  `Drive belt tensioner install`,
  `Ac refrigerant recharge`,
];
